---
- name: install libatomic
  command: yast -i libatomic1

- name: add swap file
  command: fallocate -l 10G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile && echo "/swapfile swap swap defaults 0 0" | tee /etc/fstab

- name: create install dir
  file:
    path: /hana/shared/install
    state: directory

- name: deploy hdblcm install template
  template:
    src: "{{ 'hdbserver_hana2.j2' if use_hana2 else 'hdbserver_hana1.j2'}}"
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_install.cfg

- name: deploy hdblcm password file
  template:
    src: hdbserver_passwords.j2
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_passwords.xml

- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /hana/shared/install/SAPCAR_LINUX.EXE
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download hdbserver
  get_url:
    url: "{{ url_hdbserver }}"
    dest: /hana/shared/install/IMDB_SERVER_LINUX.SAR
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: extract hdbserver
  command: ./SAPCAR_LINUX.EXE -manifest SIGNATURE.SMF -xvf IMDB_SERVER_LINUX.SAR
  args:
    chdir: /hana/shared/install
    creates: /hana/shared/install/SAP_HANA_DATABASE/hdblcm

- name: add workaround
  command: echo "127.0.0.1 SLANALYTICSFTP.wdf.sap.corp" >> /etc/hosts

- name: run hdblcm
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_{{ sap_sid }}_install.cfg' --read_password_from_stdin=xml"
  args:
    chdir: /hana/shared/install/SAP_HANA_DATABASE

- name: configure hdb
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); rm ../hdbserver_{{ sap_sid }}_passwords.xml; echo $pwd | hdbsql -i 01 -d SYSTEMDB -u SYSTEM -p $pwd \"CREATE DATABASE HDB SYSTEM USER PASSWORD $pwd\""
  args:
    chdir: /hana/shared/install/SAP_HANA_DATABASE

- name: download s4core
  get_url:
    url: "URL"
    dest: /hana/shared/install/S4Core.zip
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: unzip s4core
  command: unzip S4Core.zip
  args:
    chdir: /hana/shared/install

- name: delete s4core
  command: rm S4Core.zip
  args:
    chdir: /hana/shared/install
