---
- name: install libatomic
  command: yast -i libatomic1

- name: add swap file
  command: fallocate -l 20G /swapfile

- name: configure swap
  command: chmod 600 /swapfile

- name: make swap
  command: mkswap /swapfile

- name: enable swap
  command: swapon /swapfile
 
- name: hang in swap
  command: echo "/swapfile swap swap defaults 0 0" | tee /etc/fstab

- name: create install dir
  file:
    path: /hana/shared/install
    state: directory

- name: deploy hdblcm install template
  template:
    src: "{{ 'hdbserver_hana2.j2' if use_hana2 else 'hdbserver_hana1.j2'}}"
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_install.cfg

- name: deploy hdblcm password file
  template:
    src: hdbserver_passwords.j2
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_passwords.xml

- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /hana/shared/install/SAPCAR_LINUX.EXE
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download hdbserver
  get_url:
    url: "{{ url_hdbserver }}"
    dest: /hana/shared/install/IMDB_SERVER_LINUX.SAR
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: extract hdbserver
  command: ./SAPCAR_LINUX.EXE -manifest SIGNATURE.SMF -xvf IMDB_SERVER_LINUX.SAR
  args:
    chdir: /hana/shared/install
    creates: /hana/shared/install/SAP_HANA_DATABASE/hdblcm

- name: run hdblcm
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_{{ sap_sid }}_install.cfg' --read_password_from_stdin=xml"
  args:
    chdir: /hana/shared/install/SAP_HANA_DATABASE

#- name: configure hdb
#  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); rm ../hdbserver_{{ sap_sid }}_passwords.xml; echo $pwd | hdbsql -i 01 -d SYSTEMDB -u SYSTEM -p $pwd \"CREATE DATABASE HDB SYSTEM USER PASSWORD $pwd\""
#  args:
#    chdir: /hana/shared/install/SAP_HANA_DATABASE

- name: download s4core
  get_url:
    url: "{{ url_s4core }}"
    dest: /hana/shared/install/S4Core.zip
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download hana client
  get_url:
    url: "{{ url_hana_client }}"
    dest: /hana/shared/install/hana_client.SAR
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: unzip s4core
  command: unzip S4Core.zip
  args:
    chdir: /hana/shared/install

- name: delete s4core
  command: rm S4Core.zip
  args:
    chdir: /hana/shared/install

- name: extract SWPM
  command: /usr/sap/HN1/HDB01/exe/SAPCAR -xvf /hana/shared/install/SWPM20SP03_7-80003424.SAR
  args:
    chdir: /hana/shared/install

- name: start sapinst
  command: /hana/shared/install/sapinst SAPINST_USE_HOSTNAME=hn1-hdb0 SAPINST_ACCEPT_INTERNAL_SIGNATURE=true SAPINST_SLP_MODE=false SAPINST_STACK_XML=/hana/shared/install/MP_Stack_1000751853_2019087_.xml
  args:
    chdir: /hana/shared/install
