---
- name: install libatomic
  command: zypper in libatomic1

- name: add swap file
  command: dd if=/dev/zero of=/hana/shared/swapfile count=21000 bs=1MiB

- file:
  path: /hana/shared/swapfile
  mode: 0600

- name: make swap
  command: mkswap /hana/shared/swapfile
 
- name: hang in swap
  lineinfile:
    dest: /etc/fstab
    regexp: "/hana/shared/swapfile"
    line: "/hana/shared/swapfile none swap sw 0 0"

- name: enable swap
  command: swapon -a

- name: create install dir
  file:
    path: /hana/shared/install
    state: directory

- name: deploy hdblcm install template
  template:
    src: "{{ 'hdbserver_hana2.j2' if use_hana2 else 'hdbserver_hana1.j2'}}"
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_install.cfg

- name: deploy hdblcm password file
  template:
    src: hdbserver_passwords.j2
    dest: /hana/shared/install/hdbserver_{{ sap_sid }}_passwords.xml

- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /hana/shared/install/SAPCAR_LINUX.EXE
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download hdbserver
  get_url:
    url: "{{ url_hdbserver }}"
    dest: /hana/shared/install/IMDB_SERVER_LINUX.SAR
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: extract hdbserver
  command: ./SAPCAR_LINUX.EXE -manifest SIGNATURE.SMF -xvf IMDB_SERVER_LINUX.SAR
  args:
    chdir: /hana/shared/install
    creates: /hana/shared/install/SAP_HANA_DATABASE/hdblcm

- name: run hdblcm
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); echo $pwd | ./hdblcm --batch --action=install --configfile='../hdbserver_{{ sap_sid }}_install.cfg' --read_password_from_stdin=xml"
  args:
    chdir: /hana/shared/install/SAP_HANA_DATABASE

- name: configure hdb
  shell: "pwd=$(<../hdbserver_{{ sap_sid }}_passwords.xml); rm ../hdbserver_{{ sap_sid }}_passwords.xml; echo $pwd | /usr/sap/HN1/HDB01/exe/hdbsql -i 01 -d SYSTEMDB -u SYSTEM $pwd 'CREATE DATABASE HDB SYSTEM USER PASSWORD $pwd'"
  args:
    chdir: /hana/shared/install/SAP_HANA_DATABASE

- name: adjust search path and apply fqdn
  shell: "sed -i '/search/d' /etc/resolv.conf && echo 'search westeurope.cloudapp.azure.com' >> /etc/resolv.conf && hostname -F /etc/hostname"

- name: download s4core
  get_url:
    url: "{{ url_s4core }}"
    dest: /hana/shared/install/s4core.zip
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: download hana client
  get_url:
    url: "{{ url_hana_client }}"
    dest: /hana/shared/install/
    mode: 0755
    timeout: "{{ url_timeout }}"
  register: result
  until: result is succeeded
  retries: "{{ url_retries_cnt }}"
  delay: "{{ url_retries_delay }}"

- name: unzip s4core
  command: unzip s4core.zip
  args:
    chdir: /hana/shared/install

- name: Delete s4core
  file:
    state: absent
    path: "/hana/shared/install/s4core.zip"

- name: extract SWPM
  command: /usr/sap/HN1/HDB01/exe/SAPCAR -xvf /hana/shared/install/SWPM20SP03_7-80003424.SAR
  args:
    chdir: /hana/shared/install

- name: start sapinst
  shell: "screen -dmS sapinst /hana/shared/install/sapinst SAPINST_USE_HOSTNAME=hn1-hdb0-pwc SAPINST_ACCEPT_INTERNAL_SIGNATURE=true SAPINST_SLP_MODE=false IS_HOST_LOCAL_USING_STRING_COMPARE=true SAPINST_STACK_XML=/hana/shared/install/MP_Stack_1000751853_2019087_.xml"
  args:
    chdir: /hana/shared/install
